name: flutter_ecommerce_app
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  responsive_builder: ^0.3.0
  cloud_firestore: ^0.14.1+1
  firebase_auth: ^0.18.1+1
  firebase_core: ^0.5.0
  shared_preferences: ^0.5.12
  fluttertoast: ^7.1.1
  image_picker: ^0.6.7+11
  firebase_storage: ^4.0.1
  flutter_staggered_grid_view: ^0.3.2
  provider: ^4.3.2+2
  path_provider: ^1.6.18
  image: ^2.1.18
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
